-- Migration: Seed sample NCLEX questions
-- Description: Insert sample questions with IRT parameters for CAT engine testing

INSERT INTO `questions` (`id`, `text`, `options`, `correct_answers`, `explanation`, `category`, `question_type`, `bloom_level`, `irt_discrimination`, `irt_difficulty`, `irt_guessing`, `difficulty`, `tags`, `is_active`) VALUES
('q001', 'A nurse is caring for a client with a nasogastric tube connected to low intermittent suction. Which of the following findings should the nurse report to the provider immediately?', '[{"id":"a","text":"Green-tinged drainage"},{"id":"b","text":"125 mL output in 8 hours"},{"id":"c","text":"Coffee-ground drainage"},{"id":"d","text":"Client reports mild nausea"}]', '["c"]', 'Coffee-ground drainage indicates old blood in the stomach and could indicate GI bleeding, which requires immediate provider notification.', 'safe_effective_care', 'multiple_choice', 'analyze', 1.2, 0.5, 0.25, 'medium', '["gastrointestinal","assessment","prioritization"]', 1),

('q002', 'A nurse is preparing to administer medications. Which of the following actions demonstrates proper medication safety?', '[{"id":"a","text":"Checking the medication against the MAR once"},{"id":"b","text":"Verifying the patient identity using name and date of birth"},{"id":"c","text":"Administering a medication labeled by another nurse"},{"id":"d","text":"Crushing an extended-release tablet for easier swallowing"}]', '["b"]', 'Using two patient identifiers (name and DOB) is a critical safety step.', 'safe_effective_care', 'multiple_choice', 'apply', 1.4, -0.5, 0.25, 'easy', '["medication safety","patient identification"]', 1),

('q003', 'A nurse is teaching a client about colorectal cancer screening. At what age should the nurse recommend the client begin screening with a colonoscopy if they have no risk factors?', '[{"id":"a","text":"40 years"},{"id":"b","text":"45 years"},{"id":"c","text":"50 years"},{"id":"d","text":"55 years"}]', '["b"]', 'Current guidelines recommend colorectal cancer screening beginning at age 45 for individuals at average risk.', 'health_promotion', 'multiple_choice', 'remember', 1.0, 0.0, 0.25, 'medium', '["cancer screening","health promotion"]', 1),

('q004', 'Which of the following vaccines should a nurse recommend for a healthy 65-year-old client? (Select all that apply)', '[{"id":"a","text":"Pneumococcal vaccine"},{"id":"b","text":"Influenza vaccine"},{"id":"c","text":"Shingles (herpes zoster) vaccine"},{"id":"d","text":"Tetanus-diphtheria booster"},{"id":"e","text":"HPV vaccine"}]', '["a","b","c","d"]', 'Adults 65 and older should receive pneumococcal, influenza, shingles vaccine, and Td booster. HPV is not recommended over 45.', 'health_promotion', 'select_all', 'apply', 1.5, 0.8, 0.1, 'hard', '["immunizations","geriatric","preventive care"]', 1),

('q005', 'A client who recently lost their spouse states, "I dont know how to go on without them." Which response by the nurse is most therapeutic?', '[{"id":"a","text":"Time heals all wounds. You will feel better soon."},{"id":"b","text":"Tell me more about what you are experiencing."},{"id":"c","text":"Have you thought about joining a support group?"},{"id":"d","text":"At least they are no longer suffering."}]', '["b"]', 'Asking the client to share more demonstrates active listening and allows the nurse to better understand the clients needs.', 'psychosocial', 'multiple_choice', 'analyze', 1.3, 0.2, 0.25, 'medium', '["therapeutic communication","grief","mental health"]', 1),

('q006', 'A nurse is assessing a client for signs of depression. Which findings should the nurse expect? (Select all that apply)', '[{"id":"a","text":"Increased energy levels"},{"id":"b","text":"Changes in sleep patterns"},{"id":"c","text":"Loss of interest in activities"},{"id":"d","text":"Difficulty concentrating"},{"id":"e","text":"Elevated mood"}]', '["b","c","d"]', 'Signs of depression include sleep disturbances, anhedonia (loss of interest), and difficulty concentrating.', 'psychosocial', 'select_all', 'understand', 1.1, -0.3, 0.1, 'easy', '["depression","assessment","mental health"]', 1),

('q007', 'A nurse is caring for a client with a new tracheostomy. Which of the following actions should the nurse take?', '[{"id":"a","text":"Keep the tracheostomy cuff deflated at all times"},{"id":"b","text":"Suction the tracheostomy every 30 minutes"},{"id":"c","text":"Keep emergency equipment at the bedside"},{"id":"d","text":"Secure ties tightly to prevent movement"}]', '["c"]', 'Emergency equipment (obturator, spare tracheostomy, suction) must be at bedside.', 'physiological_basic', 'multiple_choice', 'apply', 1.4, 0.3, 0.25, 'medium', '["tracheostomy","airway management","safety"]', 1),

('q008', 'A nurse is teaching a client about a high-fiber diet. Which foods should the nurse include in the teaching?', '[{"id":"a","text":"White rice and white bread"},{"id":"b","text":"Legumes and whole grains"},{"id":"c","text":"Chicken and fish"},{"id":"d","text":"Cheese and milk"}]', '["b"]', 'Legumes and whole grains are high in fiber. White rice/bread are refined and low in fiber.', 'physiological_basic', 'multiple_choice', 'understand', 0.9, -0.8, 0.25, 'easy', '["nutrition","fiber","diet teaching"]', 1),

('q009', 'A nurse is caring for a client receiving IV potassium chloride. Which of the following assessments is the priority?', '[{"id":"a","text":"Urine output"},{"id":"b","text":"Blood glucose level"},{"id":"c","text":"Cardiac rhythm"},{"id":"d","text":"Temperature"}]', '["c"]', 'Potassium imbalances can cause life-threatening cardiac dysrhythmias. Cardiac rhythm monitoring is essential.', 'physiological_complex', 'multiple_choice', 'analyze', 1.6, 0.6, 0.25, 'medium', '["electrolytes","IV therapy","cardiac","prioritization"]', 1),

('q010', 'A client with heart failure has the following ABG results: pH 7.32, PaCO2 48 mmHg, HCO3 26 mEq/L. How should the nurse interpret these results?', '[{"id":"a","text":"Respiratory acidosis, uncompensated"},{"id":"b","text":"Respiratory alkalosis, compensated"},{"id":"c","text":"Metabolic acidosis, uncompensated"},{"id":"d","text":"Metabolic alkalosis, compensated"}]', '["a"]', 'pH is low (acidosis), PaCO2 is high (respiratory cause), and HCO3 is normal (no compensation). This indicates uncompensated respiratory acidosis.', 'physiological_complex', 'multiple_choice', 'analyze', 1.8, 1.2, 0.25, 'hard', '["ABGs","acid-base balance","respiratory","critical care"]', 1),

('q011', 'A nurse is calculating the drip rate for an IV infusion. The order is for 1000 mL of NS to infuse over 8 hours. The drop factor is 15 gtt/mL. What is the correct drip rate in gtt/min?', '[{"id":"a","text":"21 gtt/min"},{"id":"b","text":"31 gtt/min"},{"id":"c","text":"42 gtt/min"},{"id":"d","text":"125 gtt/min"}]', '["b"]', 'Drip rate = (Volume x Drop factor) / (Time in minutes). (1000 x 15) / (8 x 60) = 31.25 gtt/min', 'physiological_basic', 'multiple_choice', 'apply', 1.3, 0.4, 0.25, 'medium', '["dosage calculation","IV therapy","math"]', 1),

('q012', 'Which of the following is the priority nursing action for a client experiencing a tonic-clonic seizure?', '[{"id":"a","text":"Insert a padded tongue blade"},{"id":"b","text":"Restrain the client extremities"},{"id":"c","text":"Turn the client to the side"},{"id":"d","text":"Administer oxygen via non-rebreather mask"}]', '["c"]', 'Turning the client to the side maintains airway patency and prevents aspiration. Never insert anything in the mouth during a seizure.', 'physiological_complex', 'multiple_choice', 'apply', 1.5, 0.1, 0.25, 'medium', '["seizures","neurological","safety","prioritization"]', 1)

ON DUPLICATE KEY UPDATE `text` = VALUES(`text`);
